name: buypartsonline
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  flutter_bloc: ^7.0.1
  http: ^0.13.4
  fluttertoast: ^8.0.7
  equatable: ^2.0.3
  badges: ^2.0.2
  flutter_staggered_grid_view: ^0.6.1
  pull_to_refresh: ^2.0.0
  razorpay_flutter: ^1.2.9
  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.13.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Regular.ttf
          weight: 500
        - asset: assets/font/Poppins-Regular.ttf
          weight: 600
        - asset: assets/font/Poppins-Regular.ttf
          weight: 700
